global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3111']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: service_name
        replacement: gateway
      - target_label: env
        replacement: dev

  - job_name: 'main-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3112']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: service_name
        replacement: main
      - target_label: env
        replacement: dev

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:3113' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: service_name
        replacement: user
      - target_label: env
        replacement: dev
