// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: proto/user-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "UserService";

export interface Empty {
}

export interface User {
  id: string;
  name: string;
  status: string;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface CreateUserRequest {
  name: string;
}

export interface GetUsersResponse {
  users: User[];
}

export const USER_SERVICE_PACKAGE_NAME = "UserService";

export interface UserServiceClient {
  getUsers(request: Empty): Observable<GetUsersResponse>;

  getUserById(request: GetUserByIdRequest): Observable<User>;

  createUser(request: CreateUserRequest): Observable<User>;
}

export interface UserServiceController {
  getUsers(request: Empty): Promise<GetUsersResponse> | Observable<GetUsersResponse> | GetUsersResponse;

  getUserById(request: GetUserByIdRequest): Promise<User> | Observable<User> | User;

  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUsers", "getUserById", "createUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
